### ISSUE TITLE
BUG: ingest-client WorkbookDownloader method auth error

### ISSUE THREAD

**Issue by arschat** [ebi-ait/dcp-ingest-central#1048]
**Describe the bug**
> Ever since ingest api was secured, when calling the [`hca_ingest.downloader.workbook.WorkbookDownloader.get_workbook_from_submission()`](https://github.com/ebi-ait/ingest-client/blob/0f205ad415566e1243758cf8a477c56a81aa2d89/hca_ingest/downloader/workbook.py) we get an authentication 401 error even if we pass the token to the `IngestApi` object used(`IngestApi.set_token("<TOKEN>")`).

**To Reproduce**
```python
from hca_ingest.api.ingestapi import IngestApi
from hca_ingest.downloader.workbook import WorkbookDownloader

token="<TOKEN>"
submission_uuid = "95720ccd-dbd8-4543-bcc7-14ed64f94ad4"

api = IngestApi(url="https://api.ingest.archive.data.humancellatlas.org/")
api.token = token
api.get_headers()

wb_d = WorkbookDownloader(api=api)
wb_d.get_workbook_from_submission(submission_uuid)
```
Returns a 401 Client Error

**Expected behaviour**
> We would expect the token from the object to be propagated and be used across methods

**Environment**
- [X] prod
- [X] staging
- [X] dev

**Comment by arschat** [comment]
I get the same 401 error when I call the [WorkbookDownloader](https://github.com/ebi-ait/ingest-client/blob/0f205ad415566e1243758cf8a477c56a81aa2d89/hca_ingest/downloader/workbook.py#L10) `get_workbook_from_submission` method.

**Comment by arschat** [comment]
Initial issue was about `IngestApi.get_all()` method that I was not able to reproduce. I did reproduce the workbook downloader issue however, so I edited the issue body.

**Comment by arschat** [comment]
Error output
```python
from hca_ingest.api.ingestapi import IngestApi
from hca_ingest.downloader.workbook import WorkbookDownloader
submission_uuid='7d16f911-bb20-4935-897f-b818589f5644'
api = IngestApi(url="https://api.ingest.archive.data.humancellatlas.org/")
api.set_token('Bearer ' + token)
wb_d = WorkbookDownloader(api=api)
wb_d.get_workbook_from_submission(submission_uuid)
```
Error output
```console
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.venv/lib/python3.9/site-packages/hca_ingest/downloader/workbook.py", line 18, in get_workbook_from_submission
    submission_entities = self.data_collector.collect_data_by_submission_uuid(submission_uuid)
  File "~/.venv/lib/python3.9/site-packages/hca_ingest/downloader/data_collector.py", line 13, in collect_data_by_submission_uuid
    entity_dict = self.__build_entity_dict(submission)
  File "~/.venv/lib/python3.9/site-packages/hca_ingest/downloader/data_collector.py", line 22, in __build_entity_dict
    linking_map = self.__get_linking_map(submission)
  File "~/.venv/lib/python3.9/site-packages/hca_ingest/downloader/data_collector.py", line 46, in __get_linking_map
    r = self.api.get(linking_map_url, headers=headers)
  File "~/.venv/lib/python3.9/site-packages/hca_ingest/api/ingestapi.py", line 71, in get
    response.raise_for_status()
  File "~/.venv/lib/python3.9/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error:  for url: https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/60cb1648e259f076612626a3/linkingMap
```

Private method [`DataCollector.__get_linking_map`](https://github.com/ebi-ait/ingest-client/blob/0f205ad415566e1243758cf8a477c56a81aa2d89/hca_ingest/downloader/data_collector.py#L45) tries to get linkingMap of a submission, that is not permitted without token and headers are not inherited from `IngestApi` instance.

**Comment by arschat** [comment]
resolved in ebi-ait/ingest-client@e682b8cae6a8da05a0253d1bf6d269b13c5ac40d
