### ISSUE TITLE
excessive traffic to LS Login servers from HCA service

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#1051]
Excessive traffic to LS Login servers from HCA service was reported by Jan Pavlíček <pavlicek@ics.muni.cz> via email.

> Hi Amnon,
I hope you enjoyed your holiday. The problem with the excessive calling of OIDC is happening again. It was happening randomly on some days. Today, our filesystem started to fill fast again with logs, and I noticed that there are 95802 calls from today. It is again a combination of /oidc/jwk HTTP/1.1” 200 and /oidc/userinfo HTTP/1.1” 200 (IP 44.203.142.234).  Could you please have a look at that?
Best regards,
Jan Pavlíček

I have asked them for logs and IP information.
I am not sure what is going on. This would br traffic coming from a browser. I am not aware of any high volume traffic. Also, don’t believe HCA ingest suddenly has a high load of users.

I believe it is a Submission Stream issue.

**Comment by amnonkhen** [comment]
more information sent from Jan:

>The IP address is 44.203.142.234, and the oidc client ID of your app is e2041c2d-9449-4468-856e-e84711cebd21. The app is just calling oidc/userinfo HTTP/1.1” 200 and /oidc/jwk HTTP/1.1” 200 for the same user repeatedly.  In the log you can see the first log message of every /userinfo endpoint call (user is perun user ID). It looks like it's doing it for every user. 

A log message is:

`Nov 14 13:32:42 elixir-idp3 44.203.142.234 [81101D65FB7B] oidc: TRACE c.m.i.o.aop.ExecutionTimeLoggingAspect - Execution of cz.muni.ics.oidc.server.connectors.PerunConnectorRpc.post([attributesManager, getAttributes, {user=49562, attrNames=[urn:perun:user:attribute-def:def:timezone, urn:perun:user:attribute-def:def:preferredLanguage, urn:perun:user:attribute-def:core:middleName]}]) finished successfully at 2024-11-14 13:32:42.867, execution took 2ms`


Checking the [Geolocation of this ip](https://tools.keycdn.com/geo?host=44.203.142.234), I see that it is in Virginia, USA and that it belongs to AWS.

![Image](https://github.com/user-attachments/assets/30551d28-0b1f-420e-aaa4-0974df4acfcd)

The output running *nslookup* on the ip:

```
❯ nslookup 44.203.142.234
Server:		172.16.1.100
Address:	172.16.1.100#53

Non-authoritative answer:
234.142.203.44.in-addr.arpa	name = ec2-44-203-142-234.compute-1.amazonaws.com.

Authoritative answers can be found from:
142.203.44.in-addr.arpa	nameserver = ns3-24-us-east-1.ec2-rdns.amazonaws.com.
142.203.44.in-addr.arpa	nameserver = ns2-24-us-east-1.ec2-rdns.amazonaws.com.
142.203.44.in-addr.arpa	nameserver = ns1-24-us-east-1.ec2-rdns.amazonaws.com.
142.203.44.in-addr.arpa	nameserver = ns4-24-us-east-1.ec2-rdns.amazonaws.com.
```

Looking for 44.203.142.23 in the aws console I found that it is the ec2 instance that runs ingest's prod k8s server.

**Comment by amnonkhen** [comment]
I asked Jan to send information about the contents of the requests sent to LS Login, specifically, the body, query string and headers. In addition, I asked for information about user 49562 that appears in the logs.

@KociOrges could this be coming from any lambda function you created for MorPhiC?

**Comment by amnonkhen** [comment]
From Jan, about the identity of user **49562**.

> It is [Enrique Ventura](https://perun.aai.lifescience-ri.eu/admin/users/49562) and his LSAAI login is [26303cbcd3ab6e0197de8d563d6383d1e95c8e35@lifescience-ri.eu](mailto:26303cbcd3ab6e0197de8d563d6383d1e95c8e35@lifescience-ri.eu) or if you use elixir scoped then [26303cbcd3ab6e0197de8d563d6383d1e95c8e35@elixir-europe.org](mailto:26303cbcd3ab6e0197de8d563d6383d1e95c8e35@elixir-europe.org)

**Comment by amnonkhen** [comment]
Next steps:
- [ ] find which component that runs on the prod k8s is sending the requests to LS login
- [ ] Ask Jan to revise their logging configuration to limit the size of the generated log files so their FS does fill up. this would reduce the urgency of the problem. _done by Amnon, 20/11, waiting for response_

**Comment by KociOrges** [comment]
> I asked Jan to send information about the contents of the requests sent to LS Login, specifically, the body, query string and headers. In addition, I asked for information about user 49562 that appears in the logs.
> 
> @KociOrges could this be coming from any lambda function you created for MorPhiC?

The only Lambda functions we have for MorPhiC are those used for publishing metadata schemas. I don’t see how this could be related to LS login requests.

**Comment by KociOrges** [comment]
I have investigated the HCA components running on the EC2 instance ip-10-70-1-111 (`44.203.142.23`) highlighted earlier. Among these, `ingest-core` was found to have log messages relevant to the Elixir authentication issue. The following log messages and their frequencies were identified, between 2024-11-25 and 2024-11-26:

**1. Cannot obtain JWKS from URL, indicating failure to fetch the JWKS key from Elixir's endpoint.**
**Occurrences**: 67

```
Caused by: com.auth0.jwk.SigningKeyNotFoundException: Cannot obtain jwks from url https://login.elixir-czech.org/oidc//jwk
    at com.auth0.jwk.UrlJwkProvider.getJwks(UrlJwkProvider.java:107)
    at com.auth0.jwk.UrlJwkProvider.getAll(UrlJwkProvider.java:113)
    at com.auth0.jwk.UrlJwkProvider.get(UrlJwkProvider.java:131)
    at org.humancellatlas.ingest.security.authn.provider.elixir.ElixirJwkVault.getPublicKey(ElixirJwkVault.java:23)
```

**2. PrematureCloseException, indicating the connection was prematurely closed before a response was received.**
**Occurrences**: 18
```
2024-11-25 22:01:02.201  WARN 7 --- [or-http-epoll-8] r.netty.http.client.HttpClientConnect    : [id: 0x10ac2421, L:/10.70.1.165:48836 ! R:login.elixir-czech.org/147.251.6.122:443] The connection observed an error

reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response

2024-11-25 22:01:02.202 ERROR 7 --- [-8080-exec-6328] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

reactor.core.Exceptions$ReactiveException: reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
	at reactor.core.Exceptions.propagate(Exceptions.java:326) ~[reactor-core-3.2.10.RELEASE.jar!/:3.2.10.RELEASE]
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:91) ~[reactor-core-3.2.10.RELEASE.jar!/:3.2.10.RELEASE]
	at reactor.core.publisher.Mono.block(Mono.java:1494) ~[reactor-core-3.2.10.RELEASE.jar!/:3.2.10.RELEASE]
	at org.humancellatlas.ingest.security.authn.provider.elixir.ElixirAaiAuthenticationProvider.retrieveUserInfo(ElixirAaiAuthenticationProvider.java:80) ~[classes!/:na]
```

**Comment by amnonkhen** [comment]
The problem on the LS Login size is not these errors, but the volume of requests to the `/userInfo` resource.
Checking the 1st URL you mentioned, `https://login.elixir-czech.org/oidc//jwk` from the browser I get a response. Did you check it from the ingest core pod?

**Comment by KociOrges** [comment]
Secondary investigation revealed multiple requests per user session. The introduction of managed access potentially further amplifying the volume of LS requests (although this was not explicitly tested).

Implemented a caching mechanism for `/userInfo` requests to reduce redundant calls to the LS endpoint. The cache is dynamically managed, using the token's `exp` claim to determine the `TTL` for each entry. Added detailed periodic log summaries to monitor authentication attempts and cache hits/ misses.

So far, logs show cache solution lowering LS calls per session.


Next Steps
- Allow time to observe real-world usage on prod environment to validate the solution’s effectiveness. 
- Share logs and metrics with the LS team to ensure our solution aligns with their expectations and confirm that LS load has decreased from their perspective.

**Comment by KociOrges** [comment]
I contacted the LS team, and they reported that the issue has stopped occurring, which suggests that the solution we implemented has effectively addressed the problem. They mentioned that they have not observed the same level of traffic or related issues since the change was made. Based on this feedback, I have updated the ticket status to `Done`.
