### ISSUE TITLE
Fix checking if a dataset is 10x or not during archiving

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#145]
Steps to reproduce:
1. Create a 10x submission
    - lib prep protocol should have the following property
```
"library_construction_method": {
"text": "10X 3' v3 sequencing",
"ontology": "EFO:0009922",
"ontology_label": "10x 3' v3 sequencing"
},
```

2. Tick the _submit to archives_ check box. Submit. 

3. Trigger the archiver. 

```
curl -X POST https://archiver.ingest.archive.data.humancellatlas.org/archiveSubmissions -H 'Content-Type: application/json' -H "Api-Key: $ARCHIVER_API_KEY" -d '{"submission_uuid": "put-ingest-submission-uuid-here", "alias_prefix": "HCA"}'
```

Actual Behavior:
Archiver logs shows
```
ingest-archiver-845f5f9f47-vp9ck ingest-archiver [_internal.py:113 -                 _log() ] 2021-01-19 19:26:05,907 - werkzeug - INFO - 10.70.1.47 - - [19/Jan/2021 19:26:05] "POST /archiveSubmissions HTTP/1.1" 200 -
ingest-archiver-845f5f9f47-vp9ck ingest-archiver [app.py:109 -        async_archive() ] 2021-01-19 19:26:09,303 - __main__ - ERROR - Could not find EFO:0008995
ingest-archiver-845f5f9f47-vp9ck ingest-archiver Traceback (most recent call last):
ingest-archiver-845f5f9f47-vp9ck ingest-archiver   File "app.py", line 99, in async_archive
ingest-archiver-845f5f9f47-vp9ck ingest-archiver     entity_map: ArchiveEntityMap = archiver.convert(manifests)
ingest-archiver-845f5f9f47-vp9ck ingest-archiver   File "/app/archiver/archiver.py", line 270, in convert
ingest-archiver-845f5f9f47-vp9ck ingest-archiver     entities = self._convert(manifest)
ingest-archiver-845f5f9f47-vp9ck ingest-archiver   File "/app/archiver/archiver.py", line 315, in _convert
ingest-archiver-845f5f9f47-vp9ck ingest-archiver     archive_entity.conversion = converter.convert(archive_entity.data)
ingest-archiver-845f5f9f47-vp9ck ingest-archiver   File "/app/archiver/converter.py", line 187, in convert
ingest-archiver-845f5f9f47-vp9ck ingest-archiver     return ena.convert_sequencing_run(hca_data)
ingest-archiver-845f5f9f47-vp9ck ingest-archiver   File "/app/archiver/ena.py", line 157, in convert_sequencing_run
ingest-archiver-845f5f9f47-vp9ck ingest-archiver     converted_data['files'] = _sq_run_files(converted_files, hca_data)
ingest-archiver-845f5f9f47-vp9ck ingest-archiver   File "/app/archiver/ena.py", line 175, in _sq_run_files
ingest-archiver-845f5f9f47-vp9ck ingest-archiver     if protocols.is_10x(_ontology_api, hca_data.get("library_preparation_protocol")):
ingest-archiver-845f5f9f47-vp9ck ingest-archiver   File "/app/utils/protocols.py", line 14, in is_10x
ingest-archiver-845f5f9f47-vp9ck ingest-archiver     return ontology_api.is_equal_or_descendant(ONTOLOGY_10x_PARENT, library_construction)
ingest-archiver-845f5f9f47-vp9ck ingest-archiver   File "/app/api/ontology.py", line 32, in is_equal_or_descendant
ingest-archiver-845f5f9f47-vp9ck ingest-archiver     return self.is_descendant(reference_obo_id, test_obo_id)
ingest-archiver-845f5f9f47-vp9ck ingest-archiver   File "/app/api/ontology.py", line 37, in is_descendant
ingest-archiver-845f5f9f47-vp9ck ingest-archiver     raise Error(f'Could not find {reference_obo_id}')
ingest-archiver-845f5f9f47-vp9ck ingest-archiver api.ontology.Error: Could not find EFO:0008995
```

Expected Behavior:
No error. And the DSP submission must be created with correct content/

Notes:
There seems to be a discrepancy between the result of findByIdAndIsDefiningOntology endpoint in HCA ontology service and the EBI ontology service. I'm still uncertain why.

https://ontology.archive.data.humancellatlas.org/api/terms/findByIdAndIsDefiningOntology?id=EFO:0008995
https://www.ebi.ac.uk/ols/api/terms/findByIdAndIsDefiningOntology?id=EFO:0008995

**Comment by aaclan-ebi** [comment]
CC @rays22 since you seem to have some clarification during the ops meeting. 

I've emailed Zoey (cc'ed @lauraclarke and @rays22 ) to ask if she has ideas on the discrepancy I mentioned above.

**Comment by rays22** [comment]
Thanks @aaclan-ebi .
I can confirm that the `findByIdAndIsDefiningOntology` endpoint does not work for any valid EFO term ID in the HCA ontology service <https://ontology.archive.data.humancellatlas.org/>.
However, there is another HCA ontology service endpoint that seems to work and returns essentially the same content as the `findByIdAndIsDefiningOntology?id=EFO:0008995` of the EBI OLS api:
<https://ontology.archive.data.humancellatlas.org/api/terms?id=EFO:0008995>.
I don't know if it helps to solve the issue, and feel free ignore my suggested endpoint alternative. :)
