### ISSUE TITLE
Fix exporter to avoid data file transfer timeout error

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#191]
Issues in the current exporting:
1. All exporter instances waits too long for the data file transfer job to finish 
2. The exporter can timeout after the maximum timeout period.

Instead of exporter doing retries with exponential backoff, we could make it more event driven by doing the file transfer first before starting to export the metadata.

**Comment by aaclan-ebi** [comment]
Could also try to increase the timeout and make the retries more frequent but need to be cautious in hitting the quota on requesting the status of the state transfer https://cloud.google.com/storage-transfer/quotas

**Comment by aaclan-ebi** [comment]
```
2021-02-18 14:17:39,215  - exporter.terra.gcs - INFO in gcs.py:151 _assert_job_complete(): Awaiting complete transfer for job transferJobs/602e56f891708e06ec032959. Waiting 8192 seconds.(total time waite
d: 8190, max wait time: 10800 seconds)
 2021-02-18 16:34:11,318  - exporter.terra.terra_listener - ERROR in terra_listener.py:116 _experiment_message_handler(): Failed to export experiment message with body: {"bundleUuid":"7d004dec-d050-4f89-8
5af-3f951f2d04bb","versionTimestamp":"2020-09-08T09:32:18.641Z","messageProtocol":null,"exportJobId":"602e56f891708e06ec032959","documentId":"5f574fa2db657458f1bdaedb","documentUuid":"7d004dec-d050-4f89-8
5af-3f951f2d04bb","callbackLink":"/processes/5f574fa2db657458f1bdaedb","documentType":"Process","envelopeId":"5f574f9cdb657458f1bdae64","envelopeUuid":"dfb86fe3-ef1f-42ed-b559-d74f4b3b3a11","index":2,"tot
al":30}
 2021-02-18 16:34:11,318  - exporter.terra.terra_listener - ERROR in terra_listener.py:117 _experiment_message_handler(): Timeout waiting for transfer job to succeed for job transferJobs/602e56f891708e06e
c032959
Traceback (most recent call last):
  File "/app/exporter/terra/gcs.py", line 90, in transfer_upload_area
    self.client.transferJobs().create(body=transfer_job.to_dict()).execute()
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 915, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 409 when requesting https://storagetransfer.googleapis.com/v1/transferJobs?alt=json returned "Requested entity already exists">
```
[https://app.zenhub.com/files/299258791/b8fe2e89-d25a-421a-bc77-494427593736/download](https://app.zenhub.com/files/299258791/b8fe2e89-d25a-421a-bc77-494427593736/download)

**Comment by jacobwindsor** [comment]
I replicated the issue with the same submission metadata that caused the issue but with dummy (small) data files and reduced the timeout of the exporter to 1 second.

Submission:https://dev.contribute.data.humancellatlas.org/submissions/detail?uuid=3c3df123-3d61-4e0b-8e75-a6f30c0d13bc

Error:

```
 2021-03-08 16:26:49,366  - exporter.terra.terra_listener - INFO in terra_listener.py:132 _experiment_message_handler(): Received experiment message for process 2aaf2bc4-a83f-471f-8ff5-fe7391ce073e (index 0 for submission 3c3df123-3d61-4e0b-8e75-a6f30c0d13bc)
 2021-03-08 16:26:51,216  - exporter.terra.gcs - INFO in gcs.py:161 _assert_job_complete(): Awaiting complete transfer for job transferJobs/604650430b033d68b6a96bf1. Waiting 2 seconds.(total time waited: 0, max wait time: 1 seconds)
 2021-03-08 16:26:53,217  - exporter.terra.terra_listener - ERROR in terra_listener.py:145 _experiment_message_handler(): Failed to export experiment message with body: {"bundleUuid":"2aaf2bc4-a83f-471f-8ff5-fe7391ce073e","versionTimestamp":"2021-03-08T16:21:44.334Z","messageProtocol":null,"exportJobId":"604650430b033d68b6a96bf1","documentId":"60464f180b033d68b6a96bbf","documentUuid":"2aaf2bc4-a83f-471f-8ff5-fe7391ce073e","callbackLink":"/processes/60464f180b033d68b6a96bbf","documentType":"Process","envelopeId":"60464f130b033d68b6a96b49","envelopeUuid":"3c3df123-3d61-4e0b-8e75-a6f30c0d13bc","index":0,"total":30}
 2021-03-08 16:26:53,217  - exporter.terra.terra_listener - ERROR in terra_listener.py:146 _experiment_message_handler(): Timeout waiting for transfer job to succeed for job transferJobs/604650430b033d68b6a96bf1
Traceback (most recent call last):
  File "/app/exporter/terra/terra_listener.py", line 133, in _experiment_message_handler
    self.terra_exporter.export(exp.process_uuid, exp.submission_uuid, exp.experiment_uuid, exp.experiment_version, exp.job_id)
  File "/app/exporter/terra/terra_exporter.py", line 24, in export
    self.dcp_staging_client.transfer_data_files(submission, project.uuid, export_job_id)
  File "/app/exporter/terra/dcp_staging_client.py", line 67, in transfer_data_files
    self.gcs_xfer.transfer_upload_area(bucket_and_key[0], bucket_and_key[1], project_uuid, export_job_id)
  File "/app/exporter/terra/gcs.py", line 101, in transfer_upload_area
    self.assert_job_complete(transfer_job.name)
  File "/app/exporter/terra/gcs.py", line 145, in assert_job_complete
    return self._assert_job_complete(job_name, 2, 0, 1)
  File "/app/exporter/terra/gcs.py", line 170, in _assert_job_complete
    return self._assert_job_complete(job_name, new_wait_time, time_waited + wait_time, max_wait_time_secs)
  File "/app/exporter/terra/gcs.py", line 149, in _assert_job_complete
    raise Exception(f'Timeout waiting for transfer job to succeed for job {job_name}')
Exception: Timeout waiting for transfer job to succeed for job transferJobs/604650430b033d68b6a96bf1

```

**Comment by jacobwindsor** [comment]
Fix works with the large submission that caused the error: https://dev.contribute.data.humancellatlas.org/submissions/detail?uuid=a0f7933c-6909-49c4-9a74-33b9cf82ddf4
