### ISSUE TITLE
Fix Ingest Client for use in other components

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/dcp-ingest-central#306]
Ingest archiver can't be merged because its use of ingest-client blocks the use of unit tests and automated deployments.
This ticket is to update ingest-client so that it's dependencies can once again run unit tests and automated deployments.
```
> pip-compile requirements.in
      ERROR: Command errored out with exit status 1:
       command: /Users/astaffer/Repos/ingest-archiver/venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/dp/q6sgzxz97r9dsfy4vmr5v05nptwv5z/T/pip-resolver-9wljglub/hca/setup.py'"'"'; __file__='"'"'/private/var/folders/dp/q6sgzxz97r9dsfy4vmr5v05nptwv5z/T/pip-resolver-9wljglub/hca/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/dp/q6sgzxz97r9dsfy4vmr5v05nptwv5z/T/pip-pip-egg-info-1lgfazof
           cwd: /private/var/folders/dp/q6sgzxz97r9dsfy4vmr5v05nptwv5z/T/pip-resolver-9wljglub/hca/
      Complete output (3 lines):
      
      This repository has been deprecated. For information about accessing Human Cell Atlas data please refer to the `Data Browser quick start guide. https://data.humancellatlas.org/guides/quick-start-guide`
      
      ----------------------------------------
Traceback (most recent call last):
  File "/Users/astaffer/Repos/ingest-archiver/venv/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/Users/astaffer/Repos/ingest-archiver/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/astaffer/Repos/ingest-archiver/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/astaffer/Repos/ingest-archiver/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/astaffer/Repos/ingest-archiver/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/astaffer/Repos/ingest-archiver/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/astaffer/Repos/ingest-archiver/venv/lib/python3.8/site-packages/piptools/scripts/compile.py", line 435, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/Users/astaffer/Repos/ingest-archiver/venv/lib/python3.8/site-packages/piptools/resolver.py", line 178, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/astaffer/Repos/ingest-archiver/venv/lib/python3.8/site-packages/piptools/resolver.py", line 277, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/Users/astaffer/Repos/ingest-archiver/venv/lib/python3.8/site-packages/piptools/resolver.py", line 386, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/Users/astaffer/Repos/ingest-archiver/venv/lib/python3.8/site-packages/piptools/repositories/local.py", line 79, in get_dependencies
    return self.repository.get_dependencies(ireq)
  File "/Users/astaffer/Repos/ingest-archiver/venv/lib/python3.8/site-packages/piptools/repositories/pypi.py", line 223, in get_dependencies
    self._dependencies_cache[ireq] = self.resolve_reqs(
  File "/Users/astaffer/Repos/ingest-archiver/venv/lib/python3.8/site-packages/piptools/repositories/pypi.py", line 186, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/Users/astaffer/Repos/ingest-archiver/venv/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 378, in _resolve_one
    dist = self._get_dist_for(req_to_install)
  File "/Users/astaffer/Repos/ingest-archiver/venv/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 330, in _get_dist_for
    dist = self.preparer.prepare_linked_requirement(req)
  File "/Users/astaffer/Repos/ingest-archiver/venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/Users/astaffer/Repos/ingest-archiver/venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 570, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/Users/astaffer/Repos/ingest-archiver/venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 60, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/Users/astaffer/Repos/ingest-archiver/venv/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 36, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/Users/astaffer/Repos/ingest-archiver/venv/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 544, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/Users/astaffer/Repos/ingest-archiver/venv/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 519, in _generate_metadata
    return generate_metadata_legacy(
  File "/Users/astaffer/Repos/ingest-archiver/venv/lib/python3.8/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 67, in generate_metadata
    call_subprocess(
  File "/Users/astaffer/Repos/ingest-archiver/venv/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 244, in call_subprocess
    raise InstallationSubprocessError(proc.returncode, command_desc)
pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by amnonkhen** [comment]
@MightyAx is this still relevant?

**Comment by MightyAx** [comment]
If I run those commands on the dev branch, adjusting for the requirements file changing name, I still get the same error.
So we have yet not fixed out ability to compile the ingest-client for use with pip.
