### ISSUE TITLE
Fix exporter error when check GCP File Transfer job status

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#325]
Error:
```
2021-05-21 18:07:26,282  - exporter.terra.terra_exporter - INFO in terra_exporter.py:56 _wait_for_data_transfer_to_complete(): Google Cloud Transfer job was successfully created..
 2021-05-21 18:07:26,283  - exporter.terra.terra_exporter - INFO in terra_exporter.py:57 _wait_for_data_transfer_to_complete(): Waiting for job to complete..
 2021-05-21 19:34:31,407  - exporter.terra.terra_listener - ERROR in terra_listener.py:88 _experiment_message_handler(): Failed to export experiment message with body: {"exportJobId":"60a7f6d361fb7f28897d8214","documentId":"60a7ed7d61fb7f28897d820e","documentUuid":"323dd87d-bb1c-4d9b-898d-297c4a97e4c3","callbackLink":"/processes/60a7ed7d61fb7f28897d820e","documentType":"process","envelopeId":"60a7ed7561fb7f28897d81ca","envelopeUuid":"ba4fbccf-455a-4ec9-ad46-e346bca7ba95","projectId":"60a7ed7c61fb7f28897d81cc","projectUuid":"962bd805-eb89-4c54-bad2-008e497d1307","index":9,"total":13}
 2021-05-21 19:34:31,408  - exporter.terra.terra_listener - ERROR in terra_listener.py:89 _experiment_message_handler(): [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/app/exporter/terra/terra_listener.py", line 76, in _experiment_message_handler
    self.terra_exporter.export(exp.process_uuid, exp.submission_uuid, exp.job_id)
  File "/app/exporter/terra/terra_exporter.py", line 38, in export
    self._wait_for_data_transfer_to_complete(export_job_id, success, transfer_job_spec)
  File "/app/exporter/terra/terra_exporter.py", line 59, in _wait_for_data_transfer_to_complete
    start_wait_time_sec, max_wait_time_sec)
  File "/app/exporter/terra/dcp_staging_client.py", line 71, in wait_for_transfer_to_complete
    self.gcs_xfer.wait_for_job_to_complete(job_name, compute_wait_time_sec, start_wait_time_sec, max_wait_time_sec)
  File "/app/exporter/terra/gcs.py", line 118, in wait_for_job_to_complete
    timeout=max_wait_time_sec
  File "/usr/local/lib/python3.7/site-packages/polling.py", line 106, in poll
    val = target(*args, **kwargs)
  File "/app/exporter/terra/gcs.py", line 115, in <lambda>
    lambda: self.is_job_complete(job_name),
  File "/app/exporter/terra/gcs.py", line 129, in is_job_complete
    response: Dict = request.execute()
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 929, in execute
    headers=self.headers,
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 222, in _retry_request
    raise exception
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google_auth_httplib2.py", line 225, in request
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1709, in request
    conn, authority, uri, request_uri, method, body, headers, redirections, cachekey,
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1424, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1347, in _conn_request
```

**Comment by aaclan-ebi** [comment]
Full log: [https://app.zenhub.com/files/299258791/a4de13a9-12de-4825-92dc-cd43e496e9d5/download](https://app.zenhub.com/files/299258791/a4de13a9-12de-4825-92dc-cd43e496e9d5/download)

**Comment by aaclan-ebi** [comment]
Duplicate of #532
