### ISSUE TITLE
Suggested project is not editable in Ingest UI

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#375]
Steps to reproduce:
1. Suggest a project in Project Catalogue
2. Go to Ingest UI and open that project
3. Click on the `Edit project` 

Expected result:
The project details are displayed and they are editable.

Actual result:
Only `Loading project...` text appears and nothing else.

**Comment by ke4** [comment]
When we open a "Suggested project" in Ingest UI we get this error report in the JS console:

```
TypeError: Cannot use 'in' operator to search for 'contributors' in null\n at MetadataFormComponent.tabIsVisible (http://localhost:4200/main.js:5731:30)\n at http://localhost:4200/main.js:5708:71\n at Array.filter (<anonymous>)\n at MetadataFormComponent.ngOnInit (http://localhost:4200/main.js:5708:52)\n at callHook (http://localhost:4200/vendor.js:39729:18)\n at callHooks (http://localhost:4200/vendor.js:39693:17)\n at executeInitAndCheckHooks (http://localhost:4200/vendor.js:39633:9)\n at refreshView (http://localhost:4200/vendor.js:46072:21)\n at refreshDynamicEmbeddedViews (http://localhost:4200/vendor.js:47417:21)\n at refreshView (http://localhost:4200/vendor.js:46077:9)"
message = "Cannot use 'in' operator to search for 'contributors' in null
```

**Comment by ke4** [comment]
The other problem lies in the `project-form.component.ts` file:

```
if (projectResource && projectResource.content &&
            !projectResource.content.hasOwnProperty('describedBy') || !projectResource.content.hasOwnProperty('schema_type'))
```

We have 2 problems with this condition:
- As we are not persisting a content when we save the suggested project in the database the content will be `null`, so the or condition will throw an error. It is easy to fix with a parentheses around the last 2 conditions. 
- We also have to persist a content for the project resource with the`describedBy` and the `schema_type` properties. If we do that the edit page is going to appear.
