### ISSUE TITLE
[Integration test] File is stuck as invalid due to validator failure in posting successful notif from upload-service

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#473]
Screenshots:

![Screenshot 2021-10-04 at 18.43.06.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/871d99ac-7bb4-4698-ac2b-57f277682b0b):

![Screenshot 2021-10-04 at 18.43.26.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/dd8b8d7b-0774-4f5f-a0ad-b02ecd51c6be)

![Screenshot 2021-10-04 at 18.43.37.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/4779b93d-87c5-4176-9208-af79ad21bdac)

There were 2 attempts to validate the file in the upload service and it was successful in 2nd attempt but the validator failed in posting the result for the second attempt

Validator logs:
```
Posting a valid report for document http://172.20.134.175/files/615b350c010ca613eafc109d
Error: Failed to transition document; document in state Invalid cannot enter state VALID
    at retrieveMetadataDocument.then (/app/dist/utils/ingest-client/ingest-client.js:96:32)
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
Failed to process message:
 {"validation_id":"61c610af-f425-4ac0-a7e5-74524a58f73f","command":"/validator /data/ba758f54-596e-4067-ad27-7d20ea5c407e/SRR3562314_1.fastq.gz","exit_code":0,"status":"completed","stdout":"{\"validation_state\": \"VALID\", \"validation_errors\": []}\n","stderr":"","duration_s":0.04212021827697754,"exception":null,"upload_area_id":"ba758f54-596e-4067-ad27-7d20ea5c407e","names":["SRR3562314_1.fastq.gz"]}
Posting a valid report for document http://172.20.134.175/files/615b3508010ca613eafc1093
Error: Failed to transition document; document in state Invalid cannot enter state VALID
    at retrieveMetadataDocument.then (/app/dist/utils/ingest-client/ingest-client.js:96:32)
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
Failed to process message:
 {"validation_id":"1a247bb6-6b01-4bd4-8a99-9e805c2a8c28","command":"/validator /data/a8a88155-09e0-49a7-8a72-8a20b433b412/SRR3562314_1.fastq.gz","exit_code":0,"status":"completed","stdout":"{\"validation_state\": \"VALID\", \"validation_errors\": []}\n","stderr":"","duration_s":0.04235720634460449,"exception":null,"upload_area_id":"a8a88155-09e0-49a7-8a72-8a20b433b412","names":["SRR3562314_1.fastq.gz"]}
```

Upload service sends an invalid message in the first attempt and Ingest stores this result.
On the second attempt, the validator sees that the metadata is already invalid and couldn't set the metadata from Invalid -> Valid again. 

This seems to be a design issue. The core and validator doesn't know that the upload service is doing a retry. When a metadata entity is set as invalid in Ingest, it should be set to draft then validating first before it can be set to valid. However, it is also as designed that when metadata is set to Draft, the validator will try to trigger another validation request to the upload-service. 

09/02 - try increasing the data file size as this never happens in real fast files

**Comment by aaclan-ebi** [comment]
An idea for fix: The "Unable to open <file>" specific error can be caught in the validator and handled by not setting the file metadata validation state to Invalid yet. Keep the state to Validating so that when the successful retry happens in the upload service, it'll be able to set the state from Validating to Valid.

**Comment by aaclan-ebi** [comment]
The root cause of this could be because the file is being requested to be validated twice, maybe we should also prevent that from happening.

**Comment by jacobwindsor** [comment]
@aaclan-ebi I'm not sure how your proposed solution would work. It's the upload service that posts the original Invalid state right? At least I can't see any logs anywhere in Validator of "Unable to open..." (nor in upload service but I'm not very familiar with Cloudwatch)

**Comment by jacobwindsor** [comment]
The two below submissions have failed with this error:

https://dev.contribute.data.humancellatlas.org/submissions/detail?uuid=b5dfaf0b-785e-49b4-891c-8513556b0099
https://dev.contribute.data.humancellatlas.org/submissions/detail?uuid=dbedbbc1-e88f-41d8-9467-1e3a9b7dd782

**Comment by gabsie** [comment]
Try investigation ideas
Do one of them - @aaclan-ebi 
If not working, move to icebox
