### ISSUE TITLE
DCP1 metadata are missing dcpVersion's

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#481]
**Steps to replicate:**
1. Find a dcp1 project
2. Find the submission link to it
2. Force set the submission to valid by sending a PUT request to commitVaild link of that submission
3. Redeploy state tracker / delete its pod to initialise and sync its state from Ingest
4. In the submission's page in the UI, tick the checkbox in submit tab to export only metadata and click submit submit button.

**Actual Behavior:**
The submission will be stuck in Exporting.
The exporter error will have the following error in logs:
```
 2021-10-04 19:59:20,999  - exporter.terra.terra_listener - ERROR in terra_listener.py:87 _experiment_message_handler(): Failed to export experiment message with body: {"exportJobId":"615b5d0e66c0c668c660ccb9","documentId":"5d25071388fa640008b4dd2c","documentUuid":"f7505819-339d-464e-8da4-d66619d5353a","callbackLink":"/processes/5d25071388fa640008b4dd2c","documentType":"process","envelopeId":"5d24eda088fa640008b02b26","envelopeUuid":"14df1f92-155c-4da2-97fc-85601dee64da","projectId":"5d24eded88fa640008b02b28","projectUuid":"e0009214-c0a0-4a7b-96e2-d6a83e966ce0","index":0,"total":99840}
 2021-10-04 19:59:20,999  - exporter.terra.terra_listener - ERROR in terra_listener.py:88 _experiment_message_handler(): strptime() argument 1 must be str, not None
Traceback (most recent call last):
  File "/app/exporter/metadata.py", line 98, in from_dict
    return MetadataResource(metadata_type, metadata_json, uuid, dcp_version, provenance, full_resource=data)
  File "/app/exporter/metadata.py", line 77, in __init__
    self.dcp_version = utils.to_dcp_version(dcp_version)
  File "/app/exporter/utils.py", line 12, in to_dcp_version
    date = parse_date_string(date_str)
  File "/app/exporter/utils.py", line 19, in parse_date_string
    return datetime.strptime(date_str, date_format)
TypeError: strptime() argument 1 must be str, not None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/exporter/terra/terra_listener.py", line 75, in _experiment_message_handler
    self.terra_exporter.export(exp.process_uuid, exp.submission_uuid, exp.job_id)
  File "/app/exporter/utils.py", line 29, in inner
    result = func(*args, **kwargs)
  File "/app/exporter/terra/terra_exporter.py", line 32, in export
    process = self.get_process(process_uuid)
  File "/app/exporter/terra/terra_exporter.py", line 72, in get_process
    return MetadataResource.from_dict(self.ingest_client.get_entity_by_uuid('processes', process_uuid))
  File "/app/exporter/metadata.py", line 100, in from_dict
    raise MetadataParseException(e)
exporter.metadata.MetadataParseException: strptime() argument 1 must be str, not None
```

**Expected Behavior:**
The submission should be exported successfully.

**Comment by Wkt8** [comment]
Alegria will work on it after #464. Necessary for #445 which is currently in waiting for downstream components work.

**Comment by aaclan-ebi** [comment]
Awaiting reply from Andrew Herbst to give me read access to DCP1 Terra bucket and get the versions and populate the dcpVersion's for the DCP1 metadata in Ingest. The exporter is failing because dcpVersion's are missing.

**Comment by amnonkhen** [comment]
@aaclan-ebi is creating a script to update dcp1 versions of metadata on DB

**Comment by ESapenaVentura** [comment]
@aaclan-ebi worked on a script to update DcpVersions - Waiting on review of PR. Once approved will run against prod

**Comment by prabh-t** [comment]
@aaclan-ebi creating the helm chart for the job to run on prod cluster. To test first.

**Comment by amnonkhen** [comment]
PR to be reviewed by devs today, then @aaclan-ebi to run in prod

**Comment by ofanobilbao** [comment]
There are comments on the PR that Alegria will address today
