### ISSUE TITLE
geo_to_hca UnboundLocalError: local variable 'fastq_map' referenced before assignment

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/dcp-ingest-central#512]
**Describe the bug**
The geo_to_hca script encounters an error and does not work when running for this [project](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE137720) 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://github.com/ebi-ait/geo_to_hca
2. Clone the repository
3. Install requirements
4. Use the geo_to_hca script "python apps/geo_to_hca.py --accession GSE1377720"
5. See error "UnboundLocalError: local variable 'fastq_map' referenced before assignment"

**Expected behaviour**
The geo_to_hca script should continue without any errors and generate a spreadsheet that is partially filled in with metadata from the GEO accession 

**Screenshots / Logs**
`(venv) (base) wteh@C02DM256ML85 geo_to_hca % python apps/geo_to_hca.py --accession PRJNA566389
Fetching study metadata for SRA study ID: PRJNA566389
Fetching fastq file names for SRA study ID: PRJNA566389
Traceback (most recent call last):
  File "/Users/wteh/PycharmProjects/geo_to_hca/apps/geo_to_hca.py", line 308, in <module>
    main()
  File "/Users/wteh/PycharmProjects/geo_to_hca/apps/geo_to_hca.py", line 202, in main
    fastq_map = fetch_fastq_names(srp_accession, list(srp_metadata['Run']))
  File "/Users/wteh/PycharmProjects/geo_to_hca/apps/geo_to_hca.py", line 57, in fetch_fastq_names
    fastq_map = parse_reads.get_fastq_from_SRA(srr_accessions)
  File "/Users/wteh/PycharmProjects/geo_to_hca/apps/utils/parse_reads.py", line 97, in get_fastq_from_SRA
    return fastq_map
UnboundLocalError: local variable 'fastq_map' referenced before assignment
`

**Links**
> If applicable, link to relevant docs or Slack conversations.

**Environment**
- [ ] prod
- [ ] staging
- [ ] dev

**Browser**
- [ ] Chrome
- [ ] Safari
- [ ] IE
- [ ] Other (please specify)

**Comment by aaclan-ebi** [comment]
adding thread on slack https://embl-ebi-ait.slack.com/archives/C016R78CDV1/p1635335337054900

**Comment by aaclan-ebi** [comment]
The exception is coming from logic in getting the data from SRA. I have also found an issue in getting the info from ENA. Fixing that as based on the logic in the script, the info from ENA is prioritised over info from SRA. However, there is still work needed to be done to fix the logic in getting info from SRA. I need more info on how XML response is parsed and the API isn't well documented. The fix in PR https://github.com/ebi-ait/geo_to_hca/pull/31 should unblock the creation of a spreadsheet for PRJNA566.
