### ISSUE TITLE
Direct archiving integration test is failing

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#526]
Here is the stack trace that related to this bug:

```
0:03:24   _envelope_is_in_state returned True
0:03:24  envelope is in Archiving.
/builds/hca/ingest-integration-tests/tests/runners/dataset_runner.py:73: ResourceWarning: unclosed file <_io.BufferedReader name='/builds/hca/ingest-integration-tests/tests/fixtures/datasets/SS2/SS2.xlsx'>
  project_uuid=project_uuid)
E
======================================================================
ERROR: test_direct_archiving (tests.test_ingest.TestRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/hca/ingest-integration-tests/tests/test_ingest.py", line 102, in test_direct_archiving
    self.ingest_to_direct_archives(TestRun.DATASET_NAME)
  File "/builds/hca/ingest-integration-tests/tests/test_ingest.py", line 62, in ingest_to_direct_archives
    self.runner.direct_archived_run(dataset_fixture, self.deployment)
  File "/builds/hca/ingest-integration-tests/tests/runners/dataset_runner.py", line 42, in direct_archived_run
    self.ingest_archiver.archive_submission(payload)
  File "/builds/hca/ingest-integration-tests/tests/ingest_agents.py", line 263, in archive_submission
    r.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: https://archiver.ingest.dev.archive.data.humancellatlas.org/archiveSubmissions
----------------------------------------------------------------------
Ran 1 test in 209.010s
FAILED (errors=1)
Cleaning up file based variables
00:00
ERROR: Job failed: exit code 1
```

**Comment by prabh-t** [comment]
@ke4 is prioritising fixing this bug.

**Comment by ke4** [comment]
This PR in the archiver fixed this issue: https://github.com/ebi-ait/ingest-archiver/pull/51
