### ISSUE TITLE
Integration test for direct archiving is failing

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#536]
Integration test is failing as archiving response with an internal server error.

```
0:02:18   _envelope_is_in_state returned True
0:02:18  envelope is in Archiving.
/builds/hca/ingest-integration-tests/tests/runners/dataset_runner.py:73: ResourceWarning: unclosed file <_io.BufferedReader name='/builds/hca/ingest-integration-tests/tests/fixtures/datasets/SS2/SS2.xlsx'>
  project_uuid=project_uuid)
E
======================================================================
ERROR: test_direct_archiving (tests.test_ingest.TestRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/hca/ingest-integration-tests/tests/test_ingest.py", line 102, in test_direct_archiving
    self.ingest_to_direct_archives(TestRun.DATASET_NAME)
  File "/builds/hca/ingest-integration-tests/tests/test_ingest.py", line 62, in ingest_to_direct_archives
    self.runner.direct_archived_run(dataset_fixture, self.deployment)
  File "/builds/hca/ingest-integration-tests/tests/runners/dataset_runner.py", line 42, in direct_archived_run
    self.ingest_archiver.archive_submission(payload)
  File "/builds/hca/ingest-integration-tests/tests/ingest_agents.py", line 263, in archive_submission
    r.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: https://archiver.ingest.dev.archive.data.humancellatlas.org/archiveSubmissions
----------------------------------------------------------------------
Ran 1 test in 143.657s
FAILED (errors=1)
Cleaning up file based variables
00:01
ERROR: Job failed: exit code 1
```

After checking the cause of this error it turned out that the username/password is not defined in kube deployment configuration.

**Comment by ofanobilbao** [comment]
@ke4 working on this. Biostudies test environment is exposed now so it is available for us to use. Karoly to work on this bug today

**Comment by ke4** [comment]
Fixes:
- https://github.com/ebi-ait/ingest-kube-deployment/pull/37
- https://github.com/ebi-ait/ingest-kube-deployment/pull/38
