### ISSUE TITLE
Unable to run the direct archiving script 

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/dcp-ingest-central#614]
**Describe the bug**
> When running the direct archiving script from the ingest-archiver repo, an error occurs 

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone the ingest-archiver repo
2. Obtain the ARCHIVER_API_KEY
3. Run the direct_archiving script using the staging environment and submission uuid `ed92c63e-af9b-49a0-a12d-be8ba423452c`
4. An error occurs 

`2022-01-14 12:44:59,126 - __main__ - INFO - Archiving has started in staging environment for submission: ed92c63e-af9b-49a0-a12d-be8ba423452c. This could take some time. Please, be patience.
2022-01-14 12:45:16,933 - __main__ - INFO - Response: {'detailed_error_message': 'The request to the BioStudies service returned a HTTP Server error.Please check the health of the BioStudies service, you may need to resubmit your request', 'error_status_code': 500, 'message': 'Archiving failed.'}
Traceback (most recent call last):
  File "/Users/wteh/PycharmProjects/ingest-archiver/submit_to_archives.py", line 118, in <module>
    archiver_response_with_urls = process_archiver_response()
  File "/Users/wteh/PycharmProjects/ingest-archiver/submit_to_archives.py", line 76, in process_archiver_response
    [f'{BIOSAMPLES_SAMPLE_URL}/{sample_accession}' for sample_accession in response_text.get('biosamples_accessions')]
TypeError: 'NoneType' object is not iterable
`

**Expected behaviour**
> Script should run and give accessions back (https://github.com/ebi-ait/ingest-archiver/blob/dev/README_for_direct_archiver.md)

![Screenshot 2022-01-14 at 14.31.09.png](https://images.zenhubusercontent.com/5fd74f67b86eb46030b3f4e3/0262bac3-0e12-4239-a452-54e6c5584937)

**Environment**
- [ ] prod
- [x] staging
- [ ] dev

**Browser**
- [ ] Chrome
- [ ] Safari
- [ ] IE
- [ ] Other (please specify)

**Comment by ke4** [comment]
I checked this issue and it looks like we are trying to submit samples that are already accessioned in BioSamples, but not owned by us. I am not sure that is possible to do. I already set up a catchup meeting with Isuru for tomorrow morning and discuss it with him.

**Comment by idazucchi** [comment]
NCBI samples are owned by someone else so we can't submit them or edit them
The error message was not user-friendly @ke4 will create a ticket for this
@ke4 and @Wkt8 to discuss on how to proceed

**Comment by yusra-haider** [comment]
@ke4 is refactoring the code

**Comment by ke4** [comment]
I checked this submission with the archiving script and here is my summary:

This is the response:
```
2022-02-01 14:05:41,914 - __main__ - INFO - Archiving has started in local environment for submission: ed92c63e-af9b-49a0-a12d-be8ba423452c. This could take some time. Please, be patience.
2022-02-01 14:53:53,256 - __main__ - INFO - Response: {'detailed_error_message': '{"timestamp":1643724519944,"status":500,"error":"Internal Server Error","exception":"java.lang.NullPointerException","message":"No message available","path":"/biosamples/samples/SAMN10272927"}', 'error_status_code': 500, 'message': 'Archiving failed.'}
2022-02-01 14:53:53,258 - __main__ - ERROR - Something went wrong while sending data/metadata to archives.
```

Unfortunately this `No message available` error message is coming from BioSamples.
I already talked with Dipayan and they are going to fix this right away and provide a better and more clear error message.
But that does not mean that we could update somebody's else sample.
The above submission is trying to do exactly that and that won't ever work.

**Comment by Wkt8** [comment]
@Wkt8 to provide another submission without accessions owned by NCBI.

**Comment by Wkt8** [comment]
https://drive.google.com/drive/folders/1YqzWhKdE0bJMZnGNNi2LvmZCFjGQV5sH
This spreadsheet created by @ESapenaVentura should be suitable. Thanks Enrique!!

**Comment by Wkt8** [comment]
The issue has been solved and completed. Other tickets have been created to deal with the issue around testing.
