### ISSUE TITLE
error in geo_to_hca for accession GSE162122: "Run"

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#855]
Problem for accession GSE162122 in geo_to_hca tool.
[Reported](https://github.com/ebi-ait/dcp-ingest-central/issues/827#issuecomment-1242217588) by @willrockout in ticket #827 but unrelated to it.

![image.png](https://images.zenhubusercontent.com/600ed297091d3ea152b83c2d/6a068b16-d65c-4009-a932-4c170a273c49)

**Comment by idazucchi** [comment]
Amnon to discuss this with Wei

**Comment by amnonkhen** [comment]
The esearch response for SRP294127 contains a "phrase not found" error.

See debug log:

```
2022-09-15 11:19:01,694 - INFO - using geo_to_hca-1.0.19
2022-09-15 11:19:01,695 - INFO - Using the HCA template file specified at: /Users/amnon/dev/geo_to_hca/template/hca_template.xlsx
2022-09-15 11:19:01,810 - INFO - Fetching SRA study ID for GEO dataset GSE162122
2022-09-15 11:19:02,423 - DEBUG - Starting new HTTPS connection (1): eutils.ncbi.nlm.nih.gov:443
2022-09-15 11:19:02,973 - DEBUG - https://eutils.ncbi.nlm.nih.gov:443 "GET /entrez/eutils/esearch.fcgi?db=gds&retmode=json&term=GSE162122 HTTP/1.1" 200 None
2022-09-15 11:19:03,582 - DEBUG - Starting new HTTPS connection (1): eutils.ncbi.nlm.nih.gov:443
2022-09-15 11:19:04,087 - DEBUG - https://eutils.ncbi.nlm.nih.gov:443 "GET /entrez/eutils/esummary.fcgi?db=gds&retmode=json&id=200162122 HTTP/1.1" 200 None
2022-09-15 11:19:04,089 - INFO - Found SRA study ID: SRP294127
2022-09-15 11:19:04,089 - INFO - Fetching study metadata for SRA study ID: SRP294127
2022-09-15 11:19:04,696 - DEBUG - Starting new HTTPS connection (1): eutils.ncbi.nlm.nih.gov:443
2022-09-15 11:19:05,434 - DEBUG - https://eutils.ncbi.nlm.nih.gov:443 "GET /entrez/eutils/esearch.fcgi?db=sra&term=SRP294127&usehistory=y&format=json HTTP/1.1" 200 None
2022-09-15 11:19:05,437 - DEBUG - esearch url:  https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=sra&term=SRP294127&usehistory=y&format=json
2022-09-15 11:19:05,437 - DEBUG - esearch response status:  200
2022-09-15 11:19:05,437 - DEBUG - esearch response content:  {"header":{"type":"esearch","version":"0.3"},"esearchresult":{"count":"0","retmax":"0","retstart":"0","querykey":"1","webenv":"MCID_6322fc18fb31902176574cda","idlist":[],"translationset":[],"querytranslation":"(SRP294127[All Fields])","errorlist":{"phrasesnotfound":["SRP294127"],"fieldsnotfound":[]},"warninglist":{"phrasesignored":[],"quotedphrasesnotfound":[],"outputmessages":["No items found."]}}}

2022-09-15 11:19:05,438 - DEBUG - srp_metadata url: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=sra&WebEnv=MCID_6322fc18fb31902176574cda&query_key=1&rettype=runinfo&retmode=text
2022-09-15 11:19:05,875 - ERROR - Error creating spreadsheet for accession GSE162122. cannot build the srp_metadata from https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=sra&WebEnv=MCID_6322fc18fb31902176574cda&query_key=1&rettype=runinfo&retmode=text: invalid response from efetch form SRP294127: missing Run column
 content:              <?xml version="1.0" encoding="UTF-8" ?>
0  <!DOCTYPE eEfetchResult PUBLIC "-//NLM//DTD ef...
1                                     <eFetchResult>
2      \t<ERROR>Empty result - nothing to do</ERROR>
3                                    </eFetchResult>
Traceback (most recent call last):
  File "/Users/amnon/dev/geo_to_hca/geo_to_hca/geo_to_hca.py", line 123, in create_spreadsheet_using_accession
    srp_metadata = sra_utils.get_srp_metadata(srp_accession)
  File "/Users/amnon/dev/geo_to_hca/geo_to_hca/utils/sra_utils.py", line 103, in get_srp_metadata
    raise RuntimeError(f'cannot build the srp_metadata from {efetch_request.url}: '
```

**Comment by Wkt8** [comment]
Spoke to Amnon - the SRP accession can't be accessed from the SRA website - the accession doesn't appear to be publicly available.

**Comment by ESapenaVentura** [comment]
@amnonkhen determined the error is that the error message is not clear - Amnon to issue a PR

**Comment by Wkt8** [comment]
Needs code review

**Comment by amnonkhen** [comment]
@willrockout the [GSE162122](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE162122) accession you mentioned has missing data. It is connected to SRP294127, which is [not available in SRA](https://www.ncbi.nlm.nih.gov/sra?term=SRP294127).
I have changed the geo_to_hca tool to show a better error message next time, but I cannot help with this specific accession.

**Comment by MightyAx** [comment]
@amnonkhen to push to production today

**Comment by amnonkhen** [comment]
@willrockout I have pushed to prod a fix that will produce better error messages on such cases where a spreadsheet cannot be generated from the input accession.

**Comment by willrockout** [comment]
Awesome! Thanks, Everyone! Should be ok to close this ticket
