### ISSUE TITLE
Ambiguous geo-to-hca spreadsheet generator error for GSE119945

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/dcp-ingest-central#878]
*Overview*
Ingest spreadsheet generator is throwing an ambiguous error I've never seen before when trying to register  GSE119945 (screenshot included)

Browser
<img width="1343" alt="Screen Shot 2022-10-10 at 9 02 41 AM" src="https://user-images.githubusercontent.com/51383714/194908633-0d08d1c5-6bbc-4637-bb5f-289a79a55813.png">

**Comment by amnonkhen** [comment]
Issue will be investigated later this week.

relevant logs:
```
[_internal.py:225 - _log() ] 2022-10-10 15:24:57,842 - werkzeug - INFO - 10.70.1.47 - - [10/Oct/2022 15:24:57] "POST /spreadsheet-from-accession?accession=GSE119945 HTTP/1.1" 500 -
Exception: Error creating spreadsheet for accession GSE119945. not well-formed (invalid token): line 1, column 0
raise Exception(f'Error creating spreadsheet for accession {accession}. {e}') from e
File "/usr/local/lib/python3.6/site-packages/geo_to_hca/geo_to_hca.py", line 227, in create_spreadsheet_using_accession
workbook = geo_to_hca.create_spreadsheet_using_accession(geo_or_srp_accession)
File "/app/broker/import_geo/routes.py", line 56, in _generate_geo_workbook
Traceback (most recent call last):
The above exception was the direct cause of the following exception:
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
File "<string>", line None
parser.feed(text)
File "/usr/local/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
return xm.fromstring(sra_url.content)
File "/usr/local/lib/python3.6/site-packages/geo_to_hca/utils/sra_utils.py", line 142, in request_accession_info
xml = sra_utils.request_accession_info(parts_list[p], accession_type=accession_type)
File "/usr/local/lib/python3.6/site-packages/geo_to_hca/utils/utils.py", line 89, in get_experimental_metadata
xml_content_result, size = get_experimental_metadata(accessions_list, accession_type=accession_type)
File "/usr/local/lib/python3.6/site-packages/geo_to_hca/utils/utils.py", line 99, in fetch_experimental_metadata
attribute_lists = utils.fetch_experimental_metadata(biosample_accessions,accession_type='biosample')
File "/usr/local/lib/python3.6/site-packages/geo_to_hca/utils/get_tab.py", line 78, in get_specimen_from_organism_tab_xls
tab_name="Specimen from organism")
File "/usr/local/lib/python3.6/site-packages/geo_to_hca/geo_to_hca.py", line 169, in create_spreadsheet_using_accession
Traceback (most recent call last):
[routes.py:58 - _generate_geo_workbook() ] 2022-10-10 15:24:57,838 - broker.import_geo.routes - ERROR - Error creating spreadsheet for accession GSE119945. not well-formed (invalid token): line 1, column 0
[geo_to_hca.py:167 - create_spreadsheet_using_accession() ] 2022-10-10 15:24:57,048 - geo_to_hca.geo_to_hca - INFO - Getting Specimen from Organism tab
[_internal.py:225 - _log() ] 2022-10-10 15:24:50,122 - werkzeug - INFO - 10.70.1.47 - - [10/Oct/2022 15:24:50] "POST /spreadsheet-from-accession?accession=GSE119945 HTTP/1.1" 500 -
Exception: Error creating spreadsheet for accession GSE119945. not well-formed (invalid token): line 1, column 0
raise Exception(f'Error creating spreadsheet for accession {accession}. {e}') from e
File "/usr/local/lib/python3.6/site-packages/geo_to_hca/geo_to_hca.py", line 227, in create_spreadsheet_using_accession
workbook = geo_to_hca.create_spreadsheet_using_accession(geo_or_srp_accession)
File "/app/broker/import_geo/routes.py", line 56, in _generate_geo_workbook
Traceback (most recent call last):
The above exception was the direct cause of the following exception:
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
File "<string>", line None
parser.feed(text)
File "/usr/local/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
return xm.fromstring(sra_url.content)
File "/usr/local/lib/python3.6/site-packages/geo_to_hca/utils/sra_utils.py", line 142, in request_accession_info
xml = sra_utils.request_accession_info(parts_list[p], accession_type=accession_type)
File "/usr/local/lib/python3.6/site-packages/geo_to_hca/utils/utils.py", line 89, in get_experimental_metadata
xml_content_result, size = get_experimental_metadata(accessions_list, accession_type=accession_type)
File "/usr/local/lib/python3.6/site-packages/geo_to_hca/utils/utils.py", line 99, in fetch_experimental_metadata
attribute_lists = utils.fetch_experimental_metadata(biosample_accessions,accession_type='biosample')
File "/usr/local/lib/python3.6/site-packages/geo_to_hca/utils/get_tab.py", line 78, in get_specimen_from_organism_tab_xls
tab_name="Specimen from organism")
File "/usr/local/lib/python3.6/site-packages/geo_to_hca/geo_to_hca.py", line 169, in create_spreadsheet_using_accession
Traceback (most recent call last):
[routes.py:58 - _generate_geo_workbook() ] 2022-10-10 15:24:50,119 - broker.import_geo.routes - ERROR - Error creating spreadsheet for accession GSE119945. not well-formed (invalid token): line 1, column 0
[geo_to_hca.py:167 - create_spreadsheet_using_accession() ] 2022-10-10 15:24:49,206 - geo_to_hca.geo_to_hca - INFO - Getting Specimen from Organism tab
[_internal.py:225 - _log() ] 2022-10-10 15:24:44,819 - werkzeug - INFO - 10.70.1.47 - - [10/Oct/2022 15:24:44] "POST /import-accession?accession=GSE119945 HTTP/1.1" 500 -
```

**Comment by amnonkhen** [comment]
same error message as #872.
