### ISSUE TITLE
Investigate fill_ontology bug

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/dcp-ingest-central#904]
**Description of the issue:**
Sometimes the fill_ontology.py script fails when it encounters `cell barcode`.
It outputs 10 options which don't match the term. If you select manual input and provide the ontology ID for `cell barcode` the program crushes.

<details>
<summary>See error message:</summary>

``` python
python3 fill_ontologies.py -s /Users/idazucchi/Documents/misc/cell_barcode_bug/FetalEmbryonicBrain.xlsx
Found exact match for term Homo sapiens (Ontology: NCBITaxon:9606)
Found exact match for term embryonic human stage (Ontology: HsapDv:0000002)
Found exact match for term normal (Ontology: PATO:0000461)
Found exact match for term week (Ontology: UO:0000034)
Found exact match for term fetal stage (Ontology: HsapDv:0000037)
Found exact match for term Count matrix (Ontology: data:3917)
10 matches found for your search term 'cell barcode' for field analysis_file.file_core.content_description.text.
1. Cell type identifier - data:2655
2. Cell line name - data:2316
3. Cell line name (exact) - data:2317
4. Cell line name (truncated) - data:2318
5. Cell line name (assonant) - data:2320
6. Cell type name - data:2892
7. Cell type accession - data:2893
8. Cell type ontology ID - data:3238
9. Cell migration track image - data:3449
10. Cell line report - data:0963
Enter the appropriate number, 'm' for manual input, 'none' to skip this term, 'q' to save progess and stop program.
m
Please input the term manually: EFO:0010198
Traceback (most recent call last):
  File "/Users/idazucchi/Documents/script/hca-ebi-wrangler-central/src/fill_ontologies.py", line 328, in <module>
    main(args)
  File "/Users/idazucchi/Documents/script/hca-ebi-wrangler-central/src/fill_ontologies.py", line 322, in main
    parse_wb(args.wb_path, wb, json_schemas, args.zooma, args.keep)
  File "/Users/idazucchi/Documents/script/hca-ebi-wrangler-central/src/fill_ontologies.py", line 292, in parse_wb
    ontology, known_iri = select_term(ontologies_dict, cell.value, programmatic_key,
  File "/Users/idazucchi/Documents/script/hca-ebi-wrangler-central/src/fill_ontologies.py", line 234, in select_term
    return select_term(ontologies_dict, term, key, schema_info, zooma, known_iri)
  File "/Users/idazucchi/Documents/script/hca-ebi-wrangler-central/src/fill_ontologies.py", line 182, in select_term
    first_key = next(iter(ontologies_dict))
TypeError: 'NoneType' object is not iterable
```

</details>

This is weird for two reasons:
1. sometimes it works or at least it worked in the past
2. there is an [exact match](https://ontology.archive.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0010198) for the term 

spreadsheet used [here](https://docs.google.com/spreadsheets/d/18tQetSPcWxUJiNxNizH3RftNJ5fkiVMs/edit?usp=sharing&ouid=113452802627011629126&rtpof=true&sd=true)

**Possible clues**
This problem occurrs with other terms in the single cell library information branch

**Acceptance criteria for the task:**
- [ ] bug can be reproduced
- [ ] tested for other terms in single cell library information branch
- [ ] bug resolved

**Comment by amnonkhen** [comment]
@idazucchi to organise a discussion

**Comment by idazucchi** [comment]
this error is fixed by deleting the pickled schemas - when the program is run again it will download the latest schemas and accept values from the newly added ontologies
